### PR TITLE
Resolve Autoconfig can lead to invalid netplan #534

### PR DESCRIPTION
**Pull request by x13-me**
Added note regarding potential broken network config

### CODE REVIEW

**Comment by igorpecovnik** [comment]
Perhaps rather note that they have to be sure that networking config are correct. Wrong settings will lead to broken network.

**Comment by x13-me** [comment]
> Perhaps rather note that they have to be sure that networking config parameters are correct. Wrong settings will lead to broken network.

What do you think of the following wording?

> No validation of this network config is performed, wrong settings will lead to broken network.

We may also include
> [Netplan.io](https://netplan.io/) is included in Armbian, this configuration method is preferred

**Comment by igorpecovnik** [comment]
> We may also include

Yes, with a note where to put the file.

**Comment by x13-me** [comment]
Proposing to change to:
> No validation of this network config is performed, wrong settings will lead to broken network.
> Armbian supports [netplan.io](https://netplan.io), this is the preferred config method.
> See [netplan guides](https://netplan.readthedocs.io/en/stable/examples/) for various example configurations.
> Netplan config is stored in `/etc/netplan/`.

Closing this PR in favour of #542

**Pull request closed without merging**
