### PR TITLE
ci(AR-1147): create gh action to generate pdf within actions

### PR DESCRIPTION
**Pull request by littlecxm**
https://armbian.atlassian.net/browse/AR-1147

need test

### CODE REVIEW

**Comment by EvilOlaf** [comment]
I dont know why this is necessary. pdf is already created within actions?

**Comment by littlecxm** [comment]
> I dont know why this is necessary. pdf is already created within actions?

cuz commit binary maybe dirty git tracking so make conflict with PR etc. :)

**Comment by EvilOlaf** [comment]
I just created a test pr and can simply merge. No conflict
https://github.com/armbian/documentation/pull/200
Just do not touch the pdf (because even why would?)

**Comment by littlecxm** [comment]
image
like this
it usually happend when you fork but not fetch upstream to latest

**Comment by EvilOlaf** [comment]
I see. 
@lanefu does this affect the way the pdf is fetched and put somewhere (if so)?

**Comment by lanefu** [comment]
@EvilOlaf this probably answers indirectly

Don't store the .pdf artifact in the git repo itself.  Just upload to releases.

In fact we should add .pdf to .gitignore

**Comment by igorpecovnik** [comment]
Yes, the same way as we have here https://github.com/armbian/configurator

**Comment by littlecxm** [comment]
@EvilOlaf merged.

**Pull request merged**
