### PR TITLE
Mention black lists

### PR DESCRIPTION
**Pull request by igorpecovnik**

### CODE REVIEW

**Comment by EvilOlaf** [comment]
I suggest to rephrase from `blacklist` to `blocklist`.
The scripts using this file obviously need this adjustment as well.

**Comment by igorpecovnik** [comment]
Usage of black lists is kind of standard even it might sound weird. Not sure if its worth doing anything here as this won't be used by anyone else but devs.

**Comment by EvilOlaf** [comment]
`denylist` would work as well.
Decision is yours. I made the suggestions :man_shrugging:

**Comment by igorpecovnik** [comment]
I know. 

Blacklist is less confusing for dev minded people telling the same thing.
https://en.wikipedia.org/wiki/Blacklist_(computing)

**Review by EvilOlaf — APPROVED** [review]

**Pull request merged**
