### PR TITLE
add hirsute

### PR DESCRIPTION
**Pull request by AndreiCherniaev**
hirsute is now works

### CODE REVIEW

**Comment by igorpecovnik** [comment]
Can remove Groovy. It was removed https://github.com/armbian/build/pull/2952

**Comment by AndreiCherniaev** [comment]
> Can remove Groovy. It was removed [armbian/build#2952](https://github.com/armbian/build/pull/2952)

"Variants are depenendend from KERNEL_TARGET definitions and supported userlands: focal, buster, bionic, stretch."
https://docs.armbian.com/Developer-Guide_Build-Preparation/

May be armbian need use list of supported kernels in one way?

**Comment by lanefu** [comment]
> May be armbian need use list of supported kernels in one way?

maybe?    not urgent

**Comment by lanefu** [comment]
thanks or the doc updates

**Comment by AndreiCherniaev** [comment]
> > May be armbian need use list of supported kernels in one way?
> 
> maybe? not urgent

I am sorry my English I don't understand... But I see list of supported kernels using in 
[1)](https://github.com/armbian/documentation/blob/master/docs/Developer-Guide_Build-Preparation.md) "Variants are depenendend from KERNEL_TARGET definitions and supported userlands: focal, buster, bionic, stretch"
[2) ](https://github.com/armbian/documentation/blob/master/docs/Developer-Guide_Build-Options.md)"RELEASE ( stretch | buster | bullseye | bionic | focal | hirsute ): set OS release manually to skip dialog prompt; use this option with KERNEL_ONLY=yes to create board support package"
3) may be somewhere else

**Comment by igorpecovnik** [comment]
With KERNEL_TARGET we define which branches are available for certain BOARD so users don't select BRANCH that is not supported. For example:
Odroid C2 doesn't have legacy kernel:
https://github.com/armbian/build/blob/master/config/boards/odroidc2.conf#L5
Odroid N2 has it (but we are thinking to remove it)
https://github.com/armbian/build/blob/master/config/boards/odroidn2.conf#L9

But this doesn't play much role for user. We decide / define what works or what not. Usually some variant is not define or its just pointless to have.

RELEASE is userland, packages relations to be more precise - derived from Debian (Strecth, Buster, ...) or Ubuntu (focal, bionic, ...)

**Pull request merged**
