### PR TITLE
[DRAFT] Starting to document the new build system

### PR DESCRIPTION
**Pull request by Miouyouyou**
Better late than never, but still almost too late for the
next release...
Anyway, this is the first draft about adding desktop
environments and appgroups.

The next step will be to document how to setup Debootstrap
and CLI packages lists.

Signed-off-by: Miouyouyou (Myy) <myy@miouyouyou.fr>

### CODE REVIEW

**Comment by igorpecovnik** [comment]
@AndreiCherniaev or anyone that have some spare time.

You might have a question how this works, but documentation is n/a, or in this unfinished stage, most of people is not faimiliar how it works ... If you need harder chellenge ;) and help us out a bit, this is it.

This merge request needs to be checked with reality - we have merged the code and we are using it to some degree. Things might be changed since and a few parts is known to miss: ([last three commit comments](https://github.com/Miouyouyou/build/commits/armbian_desktop)), also [this](https://github.com/armbian/build/pull/2972), perhaps something else. If you are not familiar with fixing this MR, open a new one.

**Comment by AndreiCherniaev** [comment]
"[For this](https://github.com/armbian/documentation/blob/b04e2dcc3c5faff66105c73374a14fa647374d5b/docs/Developer-Guide_Build-PackagesDefinitions.md), create this packages list directory architecture inside a subdirectory custom/boards/${BOARD}."
Can you provide full path since armbian's /build ? I don't understand _custom/boards/${BOARD}_ ...

**Comment by igorpecovnik** [comment]
Changes between sub variants are small so in 99% we don't need to have different build targets. We / armbian maintainers define unique board name. Usually we just re-use hw vendor board naming.

**Comment by AndreiCherniaev** [comment]
> Changes between sub variants are small so in 99% we don't need to have different build targets for a, b or c. We / armbian maintainers define unique board name. Usually we just re-use hw vendor board naming.

Ok, but for Orange Pi 4 I think the first question of armbian user
-what is correct ${BOARD} ? 
So may be armbian should provide full list of ${BOARD}s via hyperlink in docs?

@Miouyouyou 
"[The](https://github.com/armbian/documentation/blob/b04e2dcc3c5faff66105c73374a14fa647374d5b/docs/Developer-Guide_Build-PackagesDefinitions.md) new build system allows you to have different minimal configurations, also called CLI configurations."
But you can [see](https://github.com/armbian/build/blob/master/config/targets.conf) desktop|cli|minimal versions. So cli != minimal... Or you suggest delete "minimal" configuration in new build system?

**Comment by AndreiCherniaev** [comment]
> @AndreiCherniaev or anyone that have some spare time.
> 
> You might have a question how this works, but documentation is n/a, or in this unfinished stage, most of people is not faimiliar how it works ... If you need harder chellenge ;) and help us out a bit, this is it.
> 
> This merge request needs to be checked with reality - we have merged the code and we are using it to some degree. Things might be changed since and a few parts is known to miss: ([last three commit comments](https://github.com/Miouyouyou/build/commits/armbian_desktop)), also [this](https://github.com/armbian/build/pull/2972), perhaps something else. If you are not familiar with fixing this MR, open a new one.

0) First of all I want exclude [cracklib](https://github.com/armbian/build/pull/2974). So I create 
/home/a/Documents/myArmbians/8armbian/build/config/desktop/hirsute/environments/xfce/config_base/custom/boards/orangepi4/packages.remove file contains:
libcrack2 cracklib-runtime

I want minicom to be installed so I create /home/a/Documents/myArmbians/8armbian/build/config/desktop/hirsute/environ
[config_base.zip](https://github.com/armbian/documentation/files/6776364/config_base.zip)
ments/xfce/config_base/custom/boards/orangepi4/packages file contains
minicom

But after build cracklib was in armbian! And no minicom!

I armbian build script
`./compile.sh  BOARD=orangepi4 BRANCH=current RELEASE=hirsute BUILD_MINIMAL=no BUILD_DESKTOP=yes KERNEL_ONLY=no KERNEL_CONFIGURE=yes  COMPRESS_OUTPUTIMAGE=sha,gpg,img BSPFREEZE=yes REPOSITORY_INSTALL="" EXTERNAL=no EXTRAWIFI=no AUFS=no WIREGUARD=no INSTALL_KSRC=yes OFFLINE_WORK=yes BSPFREEZE=yes CREATE_PATCHES=yes`

**Comment by igorpecovnik** [comment]
> First of all I want exclude cracklib. So I create

Start studying documentation, check logs and try again. You don't expect you will master build system in a few days or weeks? Also sheck support terms once again - you are deep in support area where you pay first, ask questions next - "[personalised support](https://github.com/armbian/build#support)". You can also help first and we will help you ... if we know and have time.

**Comment by AndreiCherniaev** [comment]
> @AndreiCherniaev or anyone that have some spare time.
> 
> You might have a question how this works, but documentation is n/a, or in this unfinished stage, most of people is not faimiliar how it works ... If you need harder chellenge ;) and help us out a bit, this is it.
> 
> This merge request needs to be checked with reality - we have merged the code and we are using it to some degree. Things might be changed since and a few parts is known to miss: ([last three commit comments](https://github.com/Miouyouyou/build/commits/armbian_desktop)), also [this](https://github.com/armbian/build/pull/2972), perhaps something else. If you are not familiar with fixing this MR, open a new one.

You ask me to test https://github.com/armbian or https://github.com/Miouyouyou/build/tree/armbian_desktop ?

P.S. Look at my another messages please.

**Comment by Miouyouyou** [comment]
@AndreiCherniaev The documentation is clearly outdated on the custom/* parts, these parts have been moved to another folder that mimic an overlay system.

Try adding your `packages.remove`  in `config/optional/boards/${BOARD}/_config/desktop/hirsute/environments/xfce/` or `config/optional/boards/${BOARD}/_config/desktop/hirsute/environments/xfce/config_base` instead.

Worse case, try just adding **packages.remove** in `config/desktop/hirsute/environments/xfce/config_base/` .

Also, is it your first time using the Armbian build scripts ?

This part of the documentation, along with these features, are targeted towards OEM implementors who mainly used scripts to generate the image, with commonly used variables, and tend to generate various images for different boards with the same scripts.  
If you're only building for one platform, adding files in the environments directories should be faster.  

`${BOARD}` is basically the name of the board selected in the configuration menu.  
The list is also available in `config/boards/` .

Indeed calling CLI configurations "minimal" is a misnomer.

Concerning CLI configurations :

* ` cli_minimal`  will be used if you answer **Image with console interface (server)** -> **Minimal image with console interface" during the configuration setup.**
* ` cli_standard` will be used if you answer **Image with console interface (server)** -> **Standard image with console interface**
* `cli_desktop` is only used to share CLI packages that are commonly used on all desktop platforms.

So the names are not that far-fetched.

**Pull request closed without merging**
