### PR TITLE
add wifi shortlist

### PR DESCRIPTION
**Pull request by EvilOlaf**

### CODE REVIEW

**Review by peter279k — APPROVED** [review]

**Comment by igorpecovnik** [comment]
We have our own database in the Wordpress, which is even more relevant, but some wordpress geek is needed to generate a nice list from it. https://www.armbian.com/wp-admin/edit.php?post_type=accessory

**Comment by EvilOlaf** [comment]
Maybe we should get rid of this list because since we have boards maintained off-site the stuff cannot be tested on all these boards as it is claimed.

**Comment by igorpecovnik** [comment]
i have all those wifi chips and can be auto tested if / when we get that far. which is still a lot better then generic "work on linux" list. I mean, still be then none ...

**Comment by EvilOlaf** [comment]
I know you have them but maintainers off-site do not.

**Review by igorpecovnik — APPROVED** [review]
it doesn't harm if we leave this in

**Pull request merged**
