### PR TITLE
Faq

### PR DESCRIPTION
**Pull request by EvilOlaf**

### CODE REVIEW

**Comment by igorpecovnik** [comment]
I'll add when possible.

**Comment by igorpecovnik** [comment]
Before releasing we have to give some native for proofreading anyway ... so lets just move one. I'll add whenever i find some time.

Thanks for review.

**Comment by lanefu** [comment]
Great work guys.  Ill add some polish tonight or tomorrow.

**Comment by EvilOlaf** [comment]
Could you do a final proof reading? 
After that I think this can be merged as initial FAQ page

**Comment by lanefu** [comment]
I wanna clean this up.   It looks like a rant still

https://github.com/armbian/documentation/blob/faq/docs/User-Guide_FAQ.md#why-is-armbian-constantly-asking-for-money-free-software-should-be-free

**Review by lanefu — APPROVED** [review]
good 'nuff

**Pull request merged**
